### ISSUE TITLE
UNKNOWN: ConnectionError

### ISSUE THREAD

**Issue by rlinux57** [sadaqatullahn/check_gunicorn#1]
Hi, 

I am using to gunicorn plugin in order to monitor gunicorn from nagios server, I am getting below error while entering command on gunicorn server: 
**Command:**
/usr/local/bin/check_gunicorn.py --casetype Avgworkers -w 1:3 -c 6:7 -st 50
**Output:**
```
UNKNOWN: ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f5d6df37690>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f5d6df37690>: Failed to establish a new connection: [Errno 111] Connection refused)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nagiosplugin/runtime.py", line 43, in wrapper
    return func(*args, **kwds)
  File "/usr/local/bin/check_gunicorn.py", line 191, in main
    case_types.get(args.casetype, run_check.error_handler )(args.casetype, args.warning, args.critical)
  File "/usr/local/bin/check_gunicorn.py", line 121, in avg_worker
    self.run_check(contextname, self.data_fetch.get_gunicorn_workers()['avg'], warning, critical)
  File "/usr/local/bin/check_gunicorn.py", line 57, in get_gunicorn_workers
    "size": 2500000
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 655, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 180, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f5d6df37690>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f5d6df37690>: Failed to establish a new connection: [Errno 111] Connection refused)

```
**python 2.7 on centos 6.9**. Kindly help me in order to get rid off this issue.

Regards,
rlinux57

**Comment by sadaqatullah** [comment]
Plugin is unable to detect your elastic search. That is what that error means. Please make sure that statsd and elasticsearch are installed

**Comment by rlinux57** [comment]
Both are installed but getting same error, Could you please let me know how to troubleshoot it further.

**Comment by sadaqatullah** [comment]
Let me recreate the problem artificially again in my system and will give your the new solution in couple of days.

**Comment by rlinux57** [comment]
Thank you. I will be waiting for your response.

**Comment by rlinux57** [comment]
Still waiting.

**Comment by sadaqatullah** [comment]
Futher development and maintenance of tool is stalled.
